use Group7;

INSERT INTO Courses (CityID, CourseName) VALUES (1, 'White Bear Yacht Club');
INSERT INTO Courses (CityID, CourseName) VALUES (1, 'Dellwood Country Club');
INSERT INTO Courses (CityID, CourseName) VALUES (2, 'Logger''s Trail Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (2, 'Oak Glen Golf Course and Event Center');
INSERT INTO Courses (CityID, CourseName) VALUES (3, 'Stone Ridge Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (4, 'Hazeltine National Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (5, 'Highland National Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (6, 'Quail Lodge & Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (7, 'Pebble Beach Golf Links');
INSERT INTO Courses (CityID, CourseName) VALUES (7, 'Peter Hay Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (7, 'Spyglass Hill Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (7, 'The Links at Spanish Bay');
INSERT INTO Courses (CityID, CourseName) VALUES (7, 'Monterey Peninsula Country Club - Shore Course');
INSERT INTO Courses (CityID, CourseName) VALUES (8, 'Pasatiempo Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (9, 'Pacific Grove Golf Links');
INSERT INTO Courses (CityID, CourseName) VALUES (38, 'Bayonet & Black Horse - Bayonet');
INSERT INTO Courses (CityID, CourseName) VALUES (38, 'Bayonet & Black Horse - Black Horse');
INSERT INTO Courses (CityID, CourseName) VALUES (10, 'Laguna Seca Golf Ranch');
INSERT INTO Courses (CityID, CourseName) VALUES (11, 'Crooked Stick Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (11, 'Woodland Country Club');
INSERT INTO Courses (CityID, CourseName) VALUES (12, 'Brickyard Crossing');
INSERT INTO Courses (CityID, CourseName) VALUES (12, 'Eagle Creek Golf Club - Pines Course');
INSERT INTO Courses (CityID, CourseName) VALUES (12, 'Eagle Creek Golf Club - Sycamore Course');
INSERT INTO Courses (CityID, CourseName) VALUES (14, 'The Donald Ross Course');
INSERT INTO Courses (CityID, CourseName) VALUES (14, 'The Pete Dye Course at French Lick');
INSERT INTO Courses (CityID, CourseName) VALUES (15, 'Tagalong Golf & Resort');
INSERT INTO Courses (CityID, CourseName) VALUES (16, 'Saint Croix National Golf & Event Center');
INSERT INTO Courses (CityID, CourseName) VALUES (17, 'Troy Burne Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (18, 'Erin Hills Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (19, 'Sand Valley Golf Resort - Sand Valley Course');
INSERT INTO Courses (CityID, CourseName) VALUES (19, 'Sand Valley Golf Resort - Mammoth Dunes Course');
INSERT INTO Courses (CityID, CourseName) VALUES (19, 'Sand Valley Golf Resort - The Sandbox Course');
INSERT INTO Courses (CityID, CourseName) VALUES (20, 'Bonita Bay Club - Marsh Course');
INSERT INTO Courses (CityID, CourseName) VALUES (20, 'Bonita Bay Club - Creekside Course');
INSERT INTO Courses (CityID, CourseName) VALUES (20, 'Bonita Bay Club - Cypress Course');
INSERT INTO Courses (CityID, CourseName) VALUES (20, 'Bonita Bay Club - Sable Course');
INSERT INTO Courses (CityID, CourseName) VALUES (20, 'Bonita Bay Club - Estero Bay Course');
INSERT INTO Courses (CityID, CourseName) VALUES (21, 'Grey Oaks Country Club - The Pine Course');
INSERT INTO Courses (CityID, CourseName) VALUES (21, 'Grey Oaks Country Club - The Palm Course');
INSERT INTO Courses (CityID, CourseName) VALUES (22, 'Streamsong Resort - Red Course');
INSERT INTO Courses (CityID, CourseName) VALUES (22, 'Streamsong Resort - Blue Course');
INSERT INTO Courses (CityID, CourseName) VALUES (23, 'The Ocean Course At Kiawah Island');
INSERT INTO Courses (CityID, CourseName) VALUES (24, 'Farm Neck Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (24, 'Old Sandwich Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (39, 'Belgrade Lakes Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (26, 'Huntsman Springs Golf Course');
INSERT INTO Courses (CityID, CourseName) VALUES (27, 'Brookhaven Country Club');
INSERT INTO Courses (CityID, CourseName) VALUES (28, 'Royal Melbourne Golf Club - East Course');
INSERT INTO Courses (CityID, CourseName) VALUES (29, 'Royal Dornoch - Championship Course');
INSERT INTO Courses (CityID, CourseName) VALUES (29, 'Royal Dornoch - Struie Course');
INSERT INTO Courses (CityID, CourseName) VALUES (30, 'Brora Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (31, 'St. Andrews - Old Course');
INSERT INTO Courses (CityID, CourseName) VALUES (31, 'St. Andrews - New Course');
INSERT INTO Courses (CityID, CourseName) VALUES (31, 'St. Andrews - Eden Course');
INSERT INTO Courses (CityID, CourseName) VALUES (32, 'Cruden Bay Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (33, 'Inverness Golf Club');
INSERT INTO Courses (CityID, CourseName) VALUES (34, 'Kingarrock');
INSERT INTO Courses (CityID, CourseName) VALUES (35, 'Elie Golf House Club');
INSERT INTO Courses (CityID, CourseName) VALUES (36, 'Kingsbarns Golf Links');
INSERT INTO Courses (CityID, CourseName) VALUES (37, 'Carnoustie Golf Links');
INSERT INTO Courses (CityID, CourseName) VALUES (37, 'Panmure Golf Club');