use Group7;

INSERT INTO Cities (StateProvID, CityName) VALUES (1, 'Dellwood');
INSERT INTO Cities (StateProvID, CityName) VALUES (1, 'Stillwater');
INSERT INTO Cities (StateProvID, CityName) VALUES (1, 'West Lakeland Township');
INSERT INTO Cities (StateProvID, CityName) VALUES (1, 'Chaska');
INSERT INTO Cities (StateProvID, CityName) VALUES (1, 'St. Paul');
INSERT INTO Cities (StateProvID, CityName) VALUES (2, 'Carmel-By-The-Sea');
INSERT INTO Cities (StateProvID, CityName) VALUES (2, 'Pebble Beach');
INSERT INTO Cities (StateProvID, CityName) VALUES (2, 'Santa Cruz');
INSERT INTO Cities (StateProvID, CityName) VALUES (2, 'Seaside');
INSERT INTO Cities (StateProvID, CityName) VALUES (2, 'Monterey');
INSERT INTO Cities (StateProvID, CityName) VALUES (3, 'Carmel');
INSERT INTO Cities (StateProvID, CityName) VALUES (3, 'Indianapolis');
INSERT INTO Cities (StateProvID, CityName) VALUES (3, 'Carmel');
INSERT INTO Cities (StateProvID, CityName) VALUES (3, 'French Lick');
INSERT INTO Cities (StateProvID, CityName) VALUES (4, 'Birchwood');
INSERT INTO Cities (StateProvID, CityName) VALUES (4, 'Somerset');
INSERT INTO Cities (StateProvID, CityName) VALUES (4, 'Hudson');
INSERT INTO Cities (StateProvID, CityName) VALUES (4, 'Hartford');
INSERT INTO Cities (StateProvID, CityName) VALUES (4, 'Nekoosa');
INSERT INTO Cities (StateProvID, CityName) VALUES (5, 'Bonita Springs');
INSERT INTO Cities (StateProvID, CityName) VALUES (5, 'Naples');
INSERT INTO Cities (StateProvID, CityName) VALUES (5, 'Bowling Green');
INSERT INTO Cities (StateProvID, CityName) VALUES (6, 'Kiawa Island');
INSERT INTO Cities (StateProvID, CityName) VALUES (13, 'Martha''s Vineyard');
INSERT INTO Cities (StateProvID, CityName) VALUES (13, 'Plymouth');
INSERT INTO Cities (StateProvID, CityName) VALUES (12, 'Driggs');
INSERT INTO Cities (StateProvID, CityName) VALUES (7, 'Farmers Branch');
INSERT INTO Cities (StateProvID, CityName) VALUES (8, 'Black Rock');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Dornoch');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Brora');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'St. Andrews');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Peterhead');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Inverness');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Cupar');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Elie');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Kingsbarns');
INSERT INTO Cities (StateProvID, CityName) VALUES (9, 'Carnoustie');